### ISSUE TITLE
Consistent padding?Margin? in #form-grid-container

### ISSUE THREAD

**Issue by lmcrean** [lmcrean/Hoverboard#25]
<img width="953" alt="image" src="https://github.com/lmcrean/Hoverboard/assets/133490867/bd4ca011-c890-4503-bb8f-7e4bec24a38a">

As you can see, input positions is inconsistent for some reason. Password appears lower down.

**Comment by lmcrean** [comment]
need to review consistency of html

**Comment by github2python** [comment]
@Imcrean , please assign it to me

**Comment by lmcrean** [comment]
```
form input[type="text"],
form input[type="password"],
form input[type="tel"],
form input[type="email"] {
  padding: 0.7em 1em;
  border: 0.15em solid black;
  border-radius: 0.7em;
  font-size: 14px;
  font-family: 'glacial indifference';
  text-align: center;
}
```

<img width="676" alt="image" src="https://github.com/lmcrean/Hoverboard/assets/133490867/ad7f226f-d9c3-41e2-b4d7-0e02ae3b45b8">
