### ISSUE TITLE
Navbar does not display hamburger anymore

### ISSUE THREAD

**Issue by lmcrean** [lmcrean/Hoverboard#30]

**Comment by lmcrean** [comment]
![fdac39ca-92f5-41b7-bd67-09196275df53](https://github.com/lmcrean/Hoverboard/assets/133490867/a534efc6-20a1-4242-aa99-cb38fe1a85a2)

**Comment by syed-anwaar** [comment]
@lmcrean You should close this issue because navbar is now showing. And if you want to tell something else, please elaborate that so that issue can be solved.

**Comment by lmcrean** [comment]
https://github.com/lmcrean/Hoverboard/commit/b627ae2a82a7d6eb194316e8e917beb9d12eea23
