### ISSUE TITLE
testimonial imgs overlapping navbar

### ISSUE THREAD

**Issue by lmcrean** [lmcrean/Hoverboard#37]
<img width="954" alt="image" src="https://github.com/lmcrean/Hoverboard/assets/133490867/f7911f0f-1bca-4fae-8756-cfb24f8421a0">

try z-index: 3 for navbar?

**Comment by Aneal07** [comment]
why don't you add margins to the testimonial images to create space between them and the navbar?

**Comment by lmcrean** [comment]
<img width="223" alt="image" src="https://github.com/lmcrean/Hoverboard/assets/133490867/c4074288-54a8-4edb-8744-7b44db4a3bdc">
